version: "3.8"

services:
  nginx-more:
    env_file:
      - project.env
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
#    volumes:
#      - ./nginx/config:/etc/nginx/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

