services:
  nginx-more:
    environment:
    - TZ=Europe/Madrid
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}:${LATEST_VERSION}
    restart: unless-stopped
    ports:
      - 80:80
      - 9020:9020
      - 443:443
    volumes:
      - ./nginx/config:/etc/nginx/
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

