version: "3.8"

services:
  nginx-more:
    container_name: rnd-multy-${CONTAINER_NAME}
    image: ${IMAGE_NAME}:${LATEST_VERSION}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/etc/nginx/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

